version: "3.2"

services:
 filebeat:
   build:
     context: filebeat_docker
   networks:
     - filebeat_docker

 elasticsearch:
   build:
     context: docker_elk/elasticsearch
   volumes:
     - type: volume
       source: elasticsearch
       target: /usr/share/elasticsearch/data
   ports:
     - 9200:9200
     - 9300:9300
   environment:
     ES_JAVA_OPTS: "-Xmx256m -Xms256m"
     discovery.type: single-node
   networks:
     - elk_stack

 logstash:
   build:
     context: docker_elk/logstash
   ports:
     - 5000:5000
     - 9600:9600
   environment:
     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
     - elk_stack
   depends_on:
     - elasticsearch

 kibana:
   build:
     context: docker_elk/kibana
   ports:
     - 5601:5601
   networks:
     - elk_stack
   depends_on:
     - elasticsearch

networks:
 elk_stack:
   driver: bridge
 filebeat_docker:
   driver: bridge

volumes:
 elasticsearch:
